# Generated by Django 3.1.7 on 2021-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
